[versions]
picasso = "2.8"
agp = "8.3.1"
kotlin = "1.9.0"
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
kotlinPlugin = "1.8.10"
flexbox = "3.0.0"
cicerone = "7.1"
viewpager2 = "1.0.0"
fragment = "1.6.2"
kotlinx-coroutines-android = "1.6.4"
facebook-shimmer = "0.5.0"


[libraries]
facebook-shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "facebook-shimmer"}
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android"}
fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment"}
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2"}
cicerone = { group = "com.github.terrakok", name = "cicerone", version.ref = "cicerone"}
google-android-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox"}
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlinPlugin"  }

